### ISSUE TITLE
`Unused argument (expand = TRUE)` in `unlink()` for `R < 4.0.0`

### ISSUE THREAD

**Issue by p-et** [ArcadeAntics/this.path#9]
When trying to install this package on an R version 3.6.3 (in a batch-run started in a SAS process, so no interaction possible) I get the following error:

![image](https://user-images.githubusercontent.com/108826319/214824981-1afdcf3e-0b6f-4d05-8f37-b54c6c311f48.png)

Error log message as text:
_Error in unlink(FILE, force = TRUE, expand = TRUE) : 
  unused argument (expand = TRUE)
Calls: install_thispathhelper
Execution halted
ERROR: configuration failed for package 'this.path'_

The error should be fixed if this line (currently: line 290) is fixed in program R/utils.R
`on.exit(unlink(my.tmpdir, recursive = TRUE, force = TRUE), add = TRUE)`

and corrected into
`on.exit(unlink(my.tmpdir, recursive = TRUE, force = TRUE, expand = TRUE), add = TRUE)`
or
`on.exit(unlink(my.tmpdir, recursive = TRUE, force = TRUE, expand = FALSE), add = TRUE)`
if the first one would lead to trouble (in testing). 

Note: I initially opened the issue here in a read-only mirror of CRAN: https://github.com/cran/this.path/issues/1#issue-1558006778

**Comment by ArcadeAntics** [comment]
I didn't realize that `expand` was a newly added argument to `unlink()` in `R 4.0.0`. I'll go fix that and make a new tarball for you to install. I'll let you know when it's available,

**Comment by ArcadeAntics** [comment]
I've made the changes and I have a new tarball ready, you can install it with:

```R
install.packages("this.path", repos = "https://raw.githubusercontent.com/ArcadeAntics/PACKAGES")
```

Let me know if you are able to install it! Or if there are any further issues. Thank you!

**Comment by ArcadeAntics** [comment]
Apologies, I had some more issues to fix regarding C function `R_removeVarFromFrame` not existing, plus some other issues for `R < 4.0.0` like function `deparse1()` doesn't exist, function `bquote()` has no argument `splice`.

All of that should be fixed now, the packages installs without warnings for me and R CMD check produces no warnings nor errors anymore. Let me know if installing the latest version:

```R
install.packages("this.path", repos = "https://raw.githubusercontent.com/ArcadeAntics/PACKAGES")
```

resolves this issue, or if there are any further issues. Thank you!

**Comment by p-et** [comment]
Thank you @ArcadeAntics for your prompt reply and all the updates! 
I regret to inform that the issue is still not solved for me.

In the environment where I need your package (a dependency of package _logr_) I have to install the package from source as there is no internet connectivity possible. I install that package with this command:
![image](https://user-images.githubusercontent.com/108826319/215038408-e24d045a-31d0-4fbf-a2dc-9e60ff6963f2.png)
`install.packages("./r_packages/this.path-main.tar.gz")`

This command works for other _tar.gz_ packages without any modifications (no other options used), so I can rule out that I used the install.packages() function call in a wrong way.

Not sure, if I did it correctly, but I downloaded your updated package of the latest version using this link:
[https://github.com/ArcadeAntics/this.path/archive/main.tar.gz](https://github.com/ArcadeAntics/this.path/archive/main.tar.gz)
I got this information from here: [Stackoverflow: How to acquire tar.gz file from github R package](https://stackoverflow.com/questions/65673466/how-to-acquire-tar-gz-file-from-github-r-package)

Using this updated package I ran into a different error:
![image](https://user-images.githubusercontent.com/108826319/215036983-a97a0cfc-9e0d-43ea-aa0f-2810899995ff.png)

Log/Error message as text:
Warning in untar2(tarfile, files, list, exdir, restore_times) :
  skipping pax global extended headers
* installing *source* package 'this.path' ...
** using staged installation
ERROR: 'configure' exists but is not executable -- see the 'R Installation and Administration Manual'
* removing '/opt/mango/R/3.6.3/lib/R/library/this.path'

I am not sure if this **unlink** issue regarding parameter _expand_ is fired because of the R version > 4.0.0 requirement, because I tried to run this analysis on an R version 3.6.3.

However there is another occurrence of the function **unlink** which might also need to be handled as in file **utils.R**. 
See program **catfile.R** at the end of the program (currently line 159):
![image](https://user-images.githubusercontent.com/108826319/215037770-423e1c89-16f8-4894-bb1d-93f5ffb5c2a9.png)
`unlink(FILE)`

FYI: When I install your package on my local R installation (R version 4.2.1) all works well.

**Comment by ArcadeAntics** [comment]
I'm absolutely certain that the issue with `unlink()` was the changes introduced in `R 4.0.0`, I've resolved that as of now.

The issue you're seeing is because you downloaded the directory source, when you're probably better off downloading the tarball itself:

```
https://raw.githubusercontent.com/ArcadeAntics/PACKAGES/src/contrib/this.path_1.2.0.4.tar.gz
```

From that tarball, 'configure' should have execute permission, whereas it doesn't from this page directly.
You can of course rename the tarball to whatever you please after downloading it.

Does installing it in this manner resolve the issue?

**Comment by p-et** [comment]
Hi @ArcadeAntics, 
Thanks again for your fast response, updates and the helping hand to get the package work.

> you're probably better off downloading the tarball itself
I have downloaded and used the package in that way.

> Does installing it in this manner resolve the issue?
Yes, it does.

The log now looks good:
![image](https://user-images.githubusercontent.com/108826319/215076634-27033d89-73c6-47eb-8834-34d58c98607d.png)
[...]
![image](https://user-images.githubusercontent.com/108826319/215076758-a590835a-0b42-4e08-b926-184c05b2815f.png)
[...]
![image](https://user-images.githubusercontent.com/108826319/215076946-bc7ba7f3-0752-437e-bd1e-431d750855cd.png)

Issue is resolved.
